export const columns = [
  {label: "ID", value: "id"},
  {label: "DATE", value: "date"},
  {label: "BRANCH", value: "branch"},
  {label: "TYPE", value: "type"},
  {label: "AMOUNT", value: "amount"},
  {label: "BANK", value: "bank"},
  {label: "REQUESTED BY (EMPLOYEE CODE)", value: "requestedBy"},
  {label: "STATUS", value: "status"},
    // "ID",
    // "DATE",
    // "BRANCH",
    // "TYPE",
    // "AMOUNT",
    // "BANK",
    // "REQUESTED BY(EMPLOYEE CODE)",
    // "STATUS",
  ];

export const transactionsData = [
  {
    id: 1,
    date: "2023-12-01",
    branch: "Thane",
    type: "full",
    amount: 1000,
    bank: "Sample Bank",
    requestedBy: "12345",
    status: "approved",
  },
  {
    id: 2,
    date: "2023-12-02",
    branch: "Navi Mumbai",
    type: "short",
    amount: 1500,
    bank: "Another Bank",
    requestedBy: "67890",
    status: "pending",
  },
  {
    id: 3,
    date: "2023-12-03",
    branch: "Mumbai",
    type: "full",
    amount: 2000,
    bank: "Different Bank",
    requestedBy: "54321",
    status: "rejected",
  },
  {
    id: 4,
    date: "2023-12-04",
    branch: "Kurla",
    type: "short",
    amount: 1200,
    bank: "Bank XYZ",
    requestedBy: "98765",
    status: "approved",
  },
  {
    id: 5,
    date: "2023-12-05",
    branch: "Vile Parle",
    type: "full",
    amount: 1800,
    bank: "Sample Bank",
    requestedBy: "23456",
    status: "pending",
  },
  {
    id: 6,
    date: "2023-12-06",
    branch: "Lower Parel",
    type: "short",
    amount: 1600,
    bank: "Another Bank",
    requestedBy: "87654",
    status: "rejected",
  },
  {
    id: 7,
    date: "2023-12-07",
    branch: "Andheri",
    type: "full",
    amount: 2200,
    bank: "Different Bank",
    requestedBy: "34567",
    status: "approved",
  },
  {
    id: 8,
    date: "2023-12-08",
    branch: "Byculla",
    type: "short",
    amount: 1300,
    bank: "Bank XYZ",
    requestedBy: "65432",
    status: "pending",
  },
];
